[project]
name = "talent-manager-backend"
version = "0.1.0"
description = "Talent Manager Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.2",
    "djangorestframework>=3.15.2",
]
