# Generated by Django 5.1.2 on 2024-11-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('skills', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('INVITED', 'Invited'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=24)),
            ],
        ),
    ]
