# Generated by Django 5.1.2 on 2024-11-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('INVITED', 'Invited'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', max_length=24),
        ),
    ]
